version: "3"

services:
  web:
    #build: .
    image: docker.io/nexryai/concorde
    restart: always
    links:
      - db
      - redis
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config:ro
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1

  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:16-alpine
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

